### ISSUE TITLE
Don't pipe directly from the web to sudo

### ISSUE THREAD

**Issue by pjbirch** [robconery/feedback#123]
imposter_pre_002.pdf: p69.  
The example executes: 
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

Can I suggest that it is not good practice to execute code directly from the web without reviewing it?
I suggest that you explain this as part of this example.

**Comment by robconery** [comment]
It’s there - I’ll move it higher up in the text.

**Comment by robconery** [comment]
I do agree with you on this, but it's right there on the nodejs home page. Also - directly beneath this command is a large red box that says "HEY" and talks directly about this.

I think I'm going to slice this chapter up, however, because it's too large and is also not terribly targeted. So - closing this for now.
