### ISSUE TITLE
PDF p. 345, possibly misleading description of Ruby

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#132]
On PDF p. 345:

> Ruby, for example,    has the MRI (Matz's Ruby    Interpreter)    which   will    read    in  a   Ruby
> file,   do  all the things  discussed   above,  then    execute things  as  needed. You have    to
> go  through the full    set of  compiler    steps   every   time    a   routine needs   to  be  executed.

One meaning of "routine" is a method/function; that meaning would render this statement untrue.  Perhaps the word "program" or "script" would be better here than "routine."

**Comment by robconery** [comment]
Thanks - I've added a blurb about YARV:

#### YARV and Ruby 1.9

An issue was raised about this during the initial feedback period because Ruby 1.9 has moved away from MRI to a different interpreter (YARV/KRI). This interpreter will compile the Ruby code to bytecode, which it can later execute in a fast way. This is different than a static compiler in that no binary file is output, but it _is_ a fast VM for running Ruby 1.9 and beyond.

**Comment by wconrad** [comment]
I like the way you worded it.  Nice.
