### ISSUE TITLE
Can't upload ePub to Google Play

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#160]
Hi Rob.

I think you had this before with the previous release. I'm trying to upload the 003 release to my Google Play account so I can read it from there, but it's not liking it.

This is usually due to invalid ePub markup. BUT...none of the validators I can find will accept a file as big as yours.

Did you fix this before somehow? The previous version uploaded OK for me.

Thanks

**Comment by robconery** [comment]
The problem I have is that (I think) the epub generated is coming out as v2 when it's v3, which is highly annoying. I _will_ have this fixed for final - but I might push something else in a week or so that I edit with Calibre. 

Which you can do right now if you want. There's a manifest file you can edit (I can't remember the name) that has the epub version. I'll have a look and update when I find.

**Comment by robconery** [comment]
This should hopefully be fixed with the next drop. I moved to iBooks Author and am proofing with Calibre... we'll see.
