### ISSUE TITLE
more technical examples?

### ISSUE THREAD

**Issue by vrtsig** [robconery/feedback#167]
I just read the new version of your chapter on P=NP and while it is much more elaborate than the first one I struggle with the example you chose. I just find it hard to think about real world problems in terms of 'is this similar to the problem of figuring out how to feed your kids'? I was not a big fan of the cat examples in the complexity chapter for the same reason but you complemented them with a more technical case and that worked for me. I know this isn't supposed to be a dry text book but for me at least choosing too colourful examples makes things more confusing than they need to be.

**Comment by robconery** [comment]
True enough - would you believe I just rewrote it AGAIN! I thought about throwing code in there but it muddles up the whole thing - people will stare at the code and not see the larger point.

Anyway - cats are gone (as is The Dinner Problem). I have a much better chapter on the way.

**Comment by vrtsig** [comment]
Big fan of the overall project, btw. Should have said that earlier :-)

**Comment by maebeale** [comment]
I liked the cats. And The Dinner Problem. But looking forward to whatever
is "even better!"

On Sep 24, 2016 12:23 PM, "Rob Conery" notifications@github.com wrote:

True enough - would you believe I just rewrote it AGAIN! I thought about
throwing code in there but it muddles up the whole thing - people will
stare at the code and not see the larger point.

Anyway - cats are gone (as is The Dinner Problem). I have a much better
chapter on the way.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/imposters-handbook/feedback/issues/167#issuecomment-249373378,
or mute the thread

**Comment by robconery** [comment]
Algorithms etc now have more code, and more reflection on Big-O, etc.
