### ISSUE TITLE
S1, page 42, a broken link

### ISSUE THREAD

**Issue by industriousparadigm** [robconery/feedback#275]
The link which reads "this detailed explanation" goes to a 404.

**Comment by robconery** [comment]
I do appreciate your time but I have no idea what you're talking about :(. Can you help me with a page number, chapter, URL? Anything?

**Comment by industriousparadigm** [comment]
You make it difficult to give feedback 😄 Just let me know if it's no longer helpful and I can stop.

The title states page 42 of season 1 🤷‍♀️ is it helpful if I repeat the information in the body of the issue? Do you have a preferred structure for issues?

**Comment by robconery** [comment]
Ah - yes didn't notice the title. In terms of making things difficult please understand that what's in your head takes a while and some explanation to get into mine. You're giving me one-sentence issues and there's not much I can go on there.

Also - this link opens just fine for me: https://medium.com/@ayanonagon/the-y-combinator-no-not-that-one-7268d8d9c46#.czis6rxni

**Comment by industriousparadigm** [comment]
Yep, it does open fine 👍 the link doesn't work for me because when I open it directly from Preview (the Mac app I use to read PDFs), it transforms the `#` symbol into `%23` and the link breaks.

Another thing - this may not be your intention, but you are coming across somewhat defensive, especially for a forum that exists mostly for your own benefit. I don't have to, but I am giving my time to point out issues that I have found in your book, and this...

> You're giving me one-sentence issues and there's not much I can go on there

...is disappointing, partly because it's just incorrect. You didn't see it at first, but the information was all there. One sentence is all that's needed for a typo/broken link issue.

**Comment by robconery** [comment]
Weird - I was opening the PDF from Preview as well... hmmm I wonder if it's because I'm using Brave. What browser are you using?

RE being defensive yeah I can see why you'd say that :) and be sure that I do appreciate the time you're spending here. The tough part for me with this and all the other GitHub projects I have is that I'm typically doing a lot of other things and trying to figure out what people are saying in issues is tough. So I need to ask for more information and what I normally want to do is to make sure I'm clear on what I want and why - and being direct like that can be off-putting I know.

In terms of being "correct"...

> You didn't see it at first, but the information was all there. One sentence is all that's needed for a typo/broken link issue.

As nicely as I can put it... I don't know what browser you're using, whether you're at work behind a firewall, maybe in a country with not the best internet, the app you're reading the PDF in (well, I know that _now_ but not _then_), your OS, and finally the URL that's giving you the 404. As we've seen - it works for me, not for you, and we still don't know why do we?

**Comment by industriousparadigm** [comment]
Fair enough Rob. This is helpful. This last paragraph is the answer I was looking for when I initially asked what format you would prefer.

I am sitting in Portugal, with a very fast and consistent connection with no firewally business going on. I am reading on my MBP with the second-to-latest OS (Catalina), and I am opening `imposters_handbook.pdf` v2.2 with Preview v11.0.

When I click the link on that page, it goes [here](https://medium.com/@ayanonagon/the-y-combinator-no-not-that-one-7268d8d9c46%23.czis6rxni).

If I copy and paste the link in a browser, same broken link.

If I open the book with Chrome instead of Preview, the link works fine.

**Comment by industriousparadigm** [comment]
Consider putting some general guidelines for feedback in the repo's readme, could save you time and help the readers 👍

**Comment by robconery** [comment]
I really should - I've been wanting to push an issue template in place but it's sooooo hard to push for more info without sounding crappy - and in the end it really does save us time and energy! Anyway - I'll do right now...

**Comment by robconery** [comment]
OK done! I've added some issue templates and updated the README and we're off! Appreciate the nudge...

So to get back on track here - is the browser opening up Safari? I've tried that with Chrome and Brave and things seem to work OK. Is your OS language set to Portuguese? I'm wondering if there are different URL sanitizing rules. 

It's weird because `#` is a perfectly acceptable URL safe character. I can't imagine why language settings would matter but... hmmm.

I'm also on Big Sur which could a thing - but you're the first to report this so I'm wondering if it's a localized thing.

**Comment by industriousparadigm** [comment]
Awesome 🙂 back to issue then!

When I click it from my Mac, it opens a tab on Chrome, my default browser. As mentioned, choosing Copy Link in Preview copies the "wrong" link too, no matter where I paste it next.

But opening/copying the same link from my iPhone XR yields the correct result in all cases. This seems to suggest the issue lives in Catalina's version of Preview and not the file itself or the browsers that we use.

At the end of the day, if no one else is having this issue, it might just be a one off or, more importantly, not worth looking into for now 🤷‍♀️ up to you of course!

**Comment by robconery** [comment]
Wow... weird. I'm going to keep this open for now - if you upgrade to Big Sur we'll know! Also - I think I have a Catalina machine sitting around here somewhere.

Thanks again - appreciate your time!

**Comment by industriousparadigm** [comment]
Upgrading as we speak...! Will revert with my findings 😉

**Comment by industriousparadigm** [comment]
After Big Sur upgrade, works fine for me directly from the PDF 😄
