### ISSUE TITLE
Functional programming and currying

### ISSUE THREAD

**Issue by hakonrossebo** [robconery/feedback#50]
Congratulations with your new book - I really like what I've read so far.

I'm only an imposter myself in functional programming myself, having only learned and used it for the last year, so have me corrected if I'm wrong here:

From your book on currying: 

> When you find yourself refactoring your code into small functions that you then sequence together, you’re currying.

To me this, sounds like function composition. From [Wikipedia](https://en.wikipedia.org/wiki/Currying), the definition is:

> In mathematics and computer science, currying is the technique of translating the evaluation of a function that takes multiple arguments (or a tuple of arguments) into evaluating a sequence of functions, each with a single argument

In Haskell, Elm and F#, every function officially only take one parameter, a function with multiple parameters is rewritten as a series of new functions, each with only one parameter.

This is described here in [Learn you a Haskell](http://learnyouahaskell.com/higher-order-functions#curried-functions) and [F# for fun and profit](https://fsharpforfunandprofit.com/posts/currying/)

See also the discussions here on [http://stackoverflow.com/questions/36314/what-is-currying](http://stackoverflow.com/questions/36314/what-is-currying)

Elixir does not have built in fuction currying:
[http://blog.patrikstorm.com/function-currying-in-elixir](http://blog.patrikstorm.com/function-currying-in-elixir)

Forgive me if I'm wrong here. I'm just trying to learn and help out.

**Comment by chrisseaton** [comment]
I'll be a little more assertive and say that I think the description of currying is just totally wrong.

The one-sentence explanation in the Elixir blog there is simple and correct. "Currying is a technique that translates a function of arity N into a sequence of functions that all have the arity 1."

The explanation and example given in the book sort of go halfway towards point-free style, which is an unrelated technique, in that they eliminate intermediate local variables, but not totally as they still name parameters.

**Comment by robconery** [comment]
Thanks gents - it's tough to dive into these topics and feel like you've found the "authoritative source" if you will. I'll share with you why I wrote what I wrote, and we can go from there. I should add that I've been told (no matter what I write) that the definition I'm using for currying is completely wrong - so I think there's some disagreement on the term.

The super short version of my answer: I went back to [Lambda Calculus](http://homepage.cs.uiowa.edu/~slonnegr/plf/Book/Chapter5.pdf) to decide on what I think _currying_ means:

> The terms “curried” and “currying” honor Haskell Curry who used the mechanism in his study of functions. Moses Schönfinkel actually developed the idea of currying before Curry, which means that it might more accurately be called “Schönfinkeling”.
> 
> The operations of currying and uncurrying a function can be expressed in the lambda calculus as
>   define Curry = λf . λx . λy . f <x,y>
>   define Uncurry = λf . λp . f (head p) (tail p)
> 
> ..provided the pairing operation <x,y> = (cons x y) and the functions (head p) and (tail p) are available, either as predefined functions or as functions de- fined in the pure lambda calculus, as we will see later.

Lambda Calculus revolves around the notion of single-argument functions that are chained together because functions are, themselves, values. 

I think we might all agree on the idea here? The problem I might be having is conveying it clearly. In modern languages the _arity_ is important but, to me, the concept of slicing a bigger function into a chain of smaller ones is really the goal. That's what I wrote.

@chrisseaton this assertion:

> The one-sentence explanation in the Elixir blog there is simple and correct. "Currying is a technique that translates a function of arity N into a sequence of functions that all have the arity 1."

You really need to go beyond arity when thinking about currying. I can easily pass a very long tuple or some convoluted list structure and have a massive function that does way too much. 

Is inline (I think) with what I wrote here and also what I wrote in the book - but note that I don't hold the Elixir blog as an authority on this.

Thoughts?

**Comment by chrisseaton** [comment]
But that part of the document you've linked to starts with:

> Lambda calculus as described above seems to permit functions of a single variable only. The abstraction mechanism allows for only one parameter at a time. However, many useful functions, such as binary arithmetic operations, require more than one parameter

I think that shows that an example with one parameter isn't going to show what currying does.

> You really need to go beyond arity when thinking about currying. I can easily pass a very long tuple or some convoluted list structure and have a massive function that does way too much.

Why do you need to go beyond arity? Currying is a mathematical operation on functions. It turns a function from one accepting a tuple of arguments to one that takes N arguments and returns one that takes N - 1 arguments. That's all it does. Arity is its reason for being.

Are you just searching around for a good way to make currying understandable beyond the theory? I don't know Elixir but this is how I'd explain it to someone using Ruby:

``` ruby
def multiply(a)
  Proc.new do |b|
    a * b
  end
end

p multiply(14).call(2)

doubler = multiply(2)

p doubler.call(14)
```

That does show the benefit in code complexity - you can see that I've taken a general function, and made it so I can specialise it for the first argument and then call it for the second later. This is _partial application_ and is possible because the function `multiply` is _curried_.

If you still aren't convinced then I'd strongly recommend you find someone else who is knowledgeable about functional programming theory to ask for another opinion, as I really do think your example and explanation are mistaken here.

**Comment by chrisseaton** [comment]
I think another way to explain this is that currying is a mathematical operation on functions. The domain of that function is functions with more than 1 argument. None of your functions in your example has more than one argument, therefore it is not possible that you have curried anything in your example.

I think you've tried with good intentions to see a software engineering design pattern beneath currying and to bring that to the front, but currying has a mathematical definition and it simply hasn't been used here.

**Comment by hakonrossebo** [comment]
I should probably  not make any comments here as I'm just a novice in functional programming :)

Slicing a bigger function into a chain of smaller ones can be a good thing to do in many cases. 

But, my understanding is that functions with many arguments are used a lot, and that languages like Haskell, Elm and F# are currying all functions "under the hood", enabling partial application. I think Scott Wlaschin explain many functional concepts in a very good way: [https://fsharpforfunandprofit.com/posts/currying/](https://fsharpforfunandprofit.com/posts/currying/)

**Comment by robconery** [comment]
I'll add a blurb about the single arity.

**Comment by allykzam** [comment]
I know this is closed now, but I just got to this section of the book and I really have to echo the earlier comments. If having a good example helps, here's two in F# (I can try to figure out the equivalent in Elixir if it would help more?):

``` FSharp
let LogError format error =
    let message = String.Format(format, error.Message, error.StackTrace)
    // Do some file IO to append the message to a log file

let DefaultErrorLogger = LogError "Default error log format here! Message was {0}, stack trace is:\n{1}"
```

In this case, the `DefaultErrorLogger` function takes advantage of currying to supply the first argument to `LogError`, and return a new function that only takes an error object. If I find that I'm using a handful of logging formats repeatedly, this saves me from writing out the same format multiple times, and means I only have one place to change each format.

``` FSharp
let BuildField parameterType parameterName =
    // Create a "string" field with the given name, and give it an empty default value
    SqlField(parameterType, parameterName, "")

let BuildStringField = BuildField typeof<string>

let MyTable =
    [
        BuildField typeof<int> "id";
        BuildStringField "First Name";
        BuildStringField "Last Name";
    ]
```

In this case, I gave myself a helper function for defining string fields without having to say `typeof<string>` each time. The new function name is long enough that maybe it isn't so helpful, but I find myself creating helper functions named `f` all the time that are basically this.

The examples in the book are certainly good ideas, and breaking big functions into smaller ones often helps immensely, but none of them actually use currying? The lambda calculus section used currying more than the functional programming section does.
