### ISSUE TITLE
Is the phrase "hardcore pornography" out of line?

### ISSUE THREAD

**Issue by tyrw** [robconery/feedback#56]
Great concept for a book, but in a field notoriously sexist and with a lot of effort directed at those taking a nontraditional route, the best foot forward is not likely to be referencing "hardcore pornography" in the opening paragraph.  It's even as part of an 8 year old comment that you say was later redacted.  It felt to me like you went out of your way to bring up porn to be "edgy", yet the comment is a total throwaway, bringing nothing to the broader discussion.  My wife is a self-taught developer, and it made me embarrassed to recommend this book given the tone set in the introduction.

So would strongly suggest you `rm -f` the intro and give it another go.

**Comment by robconery** [comment]
I think you and I might have different ideas RE sexism. I don't equate sexism to pornography in any way. I didn't "go out of my way" and, friend, I don't appreciate your efforts to skewer me on this. 

Simple solution: *don't buy the book*.

**Comment by robconery** [comment]
I've taken 24 hours away from this comment to properly get my thoughts around it. It will be a lengthy response - one that might get me in trouble. The TL;DR is this: _I'm not going to remove Jeff's words_.

What you've done here is clumsy, and moreover it's aggressively careless. You've willfully stripped the context from the quote and handed me a bit of an accusation:

> It felt to me like you went out of your way to bring up porn to be "edgy", yet the comment is a total throwaway, bringing nothing to the broader discussion.

This is a _mediocre_ and _lazy_ assertion on your part. You saw the word "pornography" and ended your thought process - deciding it was easier to assign some sexist motive on my part. 

I'll respond in length now - read if you want to. This is mostly for readers of the book in the future who might stumble on this issue and wonder about my thoughts.

Below are my reasons for leaving the phrase in the book.

## 1: I Won't Edit Someone Else's Words

I asked a number of women (some friends, some new customers) about the term "hardcore pornography" in the book. Each time I received a variation of this response:

> the term "hardcore pornography" doesn't belong a dev book, period.

I understand _precisely_ why they feel this way. I understand it's a trigger. This phrase, sitting all alone like that, is a small word bomb. Stripped of context I probably would agree with this statement 100%, every time. That's the problem when you strip the context from a term.

Let's revisit the entire quote from [Jeff's post](https://blog.codinghorror.com/your-favorite-np-complete-cheat/):

> Have you ever heard a software engineer refer to a problem as "NP-complete"? That's fancy computer science jargon shorthand for "incredibly hard":
> 
> ...
> 
> You do want to be an expert programmer, don't you? Of course you do!
> 
> NP-complete problems are like hardcore pornography. Nobody can define what makes a problem NP-complete, exactly, but you'll [know it when you see it](https://en.wikipedia.org/wiki/I_know_it_when_I_see_it). Just this once, I'll refrain from my usual practice of inserting images to illustrate my point.
> 
> (Update: I was shooting for a poetic allusion to the P=NP problem here but based on the comments this is confusing and arguably incorrect. So I'll redact this sentence. Instead, I point you to this P=NP poll (pdf); read the comments from CS professors (including Knuth) to get an idea of how realistic this might be.)

Jeff picked the term "hardcore pornography" because the phrase "I know it when I see it" came from a supreme court case called [Jacobellis v. Ohio](https://en.wikipedia.org/wiki/Jacobellis_v._Ohio) in which the court deliberated on obscenity. 

I'll spell this out: Jeff thought the term "I'll know it when I see it" applied very well to how people think about NP-Complete problems (which was off base as it turns out). He expanded on that term to its historical roots - which is what Jeff does as a writer. It's what makes him great at what he does.

Because he used these terms to underscore his ideas, I decided to leave the entire phrase in. I _did indeed_ have a mental check on it when I included it - and ultimately decided what a lot of writers decide: _you don't get to edit someone else's words_. That's not cool. [Jeff found this out](https://blog.codinghorror.com/what-can-men-do/).

If the term still irritates you - I might suggest you take it up with Jeff; those words are his and they are included in my book because I won't edit Jeff.

## 2: You Get To Do Your Part As A Reader

As I mention above, what you've done here is _lazy_. You saw a phrase, it triggered something in you, and instead of reading more about why I included all of Jeff's quote (or, you know, maybe _asking_ me instead of _accusing_ me), you decided that I was going for "edginess". 

I think that's sloppy reasoning. I don't know what books you read, what shows you watch, or the conversations you engage in but I have to believe that you're made of more stuff than this. 

## Finally: Let's Discuss Porn

On behalf of my gay & lesbian friends, transgender, cross-dresser, cos-player, furry fandom and black leather/booty whippin dungeon masters: _porn is not the sole domain of the straight white guy_. 

**Straight guys don't get to own the word "pornography"**. 

Your assertion makes you seem a little out of touch with the larger world - especially outside of the US.

## Closing, And a Personal Note

It's important to stand up when you see something that you think is inappropriate but I might suggest that trying to see the good in other people before you see the bad will go a long way in life and your career.

You and I could have had a better dialog on this. We _should have_ had a better dialog on this.
