### ISSUE TITLE
MIssing word on page 128

### ISSUE THREAD

**Issue by raymondlewallen** [robconery/feedback#65]
I think there is a word missing in here:  "In other we don't know - so let's call that n."

**Comment by robconery** [comment]
Context?

**Comment by maebeale** [comment]
It's in para 3 of `O(n) In The Real World: Select N+1`

Prob supposed to be 'In other words, we don't...' ?

On Aug 23, 2016 5:39 PM, "Rob Conery" notifications@github.com wrote:

Context?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/imposters-handbook/feedback/issues/65#issuecomment-241888612,
or mute the thread

**Comment by raymondlewallen** [comment]
O(n) in the real world: Select N+1
