### ISSUE TITLE
Small Factual Typo on Page 132

### ISSUE THREAD

**Issue by zoffixznet** [robconery/feedback#66]
In the `O(log n) and O(n log n)` section on page 132, in the sentence below, I think it should read "increase" logarithmically, rather than "decrease":

> Here we see that the O(n^2) operations _increase_ exponentially and n increases. That's bad. 
> However O(log n) (and n log n) **_decrease**_ logarithmically over time.

**Comment by robconery** [comment]
Ah - yes good point thank you. I'll rephrase that.

**Comment by heintz** [comment]
There are a few related problems here:
- O(n^2) doesn't increase exponentially, but rather polynomially.
- O(n log n) increases faster than O(n), but more slowly than O(n^2) (after all, log(n) grows with n).  The yellow curve should therefore be between the orange and blue rather than below the orange.
- The axis labels appear to be flipped: time is on the vertical while n is on the horizontal.

**Comment by robconery** [comment]
I was just thinking this through; this whole graph/thing got borked. In the first round of feedback it was suggested I flip the axes and I did - for some reason it made sense.

Anyway: the problem is that I'm including time, which has nothing to do with order N - I should be putting _cats_ in on the Y axis. 

Cheers...

**Comment by sjsyrek** [comment]
I saw this too. However you do the graph, isn't the wording slightly misleading since you suggest that log n and n log n are the same?

http://bigocheatsheet.com/

**Comment by robconery** [comment]
All set and fixed.
