### ISSUE TITLE
NP-hard and Undecidability

### ISSUE THREAD

**Issue by racko** [robconery/feedback#93]
In the "NP-hard" section it sounds like undecidability is of special importance in this context. It is not. The proof that the halting problem is NP-hard is not central to NP-hardness; it is merely "coincidental".

[Nondeterminism](https://en.wikipedia.org/wiki/Nondeterministic_algorithm) _is_ central to NP, NP-hard and NP-complete, but that is a different concept.

**Comment by robconery** [comment]
This is the quote:

> Turing proved it (as you'll read later) and showed that it was _undecidable_... That "undecidable" part is what makes this problem NP-Hard.

You're saying, essentially, "no it's coincidental" and leaving it at that. This doesn't help me understand your point, I'm afraid. You're also not giving me enough to go on by offering a link - in other words I have no grounding in whatever your reasoning is.

So maybe explain _why you think_ the halting problem is NP-hard? Perhaps you can suggest more concretely that my assertion is wrong?

Thanks!

**Comment by robconery** [comment]
Alright! I completely rewrote this chapter... going to be quite curious what you think. I feel _very_ positive RE my understanding. WRT halting and NP-hard... I got into a rather animated discussion with my brother about this and I think I agree with him - halting is way outside of NP Hard though, literally, you can say that it is because the definition of NP-hard is "at least as hard as problems in NP". 

The truth of it is that halting is outside R even - in infinite complexity :). An update is coming in a few hours.
